/**
 * Compact callback_data encoding for pagination (Phase 8 brief §19, §60):
 * `pg:{viewId}:{page}` — never JSON, filters, captions, or a Telegram
 * user id. `viewId` is a short, URL/callback-safe id (base64url, no `:`
 * in its alphabet) generated by db/repositories/result-views.ts.
 */
const CALLBACK_PREFIX = "pg";
/** Telegram's hard limit (brief §19, §75) — measured in bytes, not JS
 * string length (this data is always ASCII, so they're equal here, but
 * byte-measuring is the honest check). */
const MAX_CALLBACK_DATA_BYTES = 64;

export function buildPaginationCallbackData(viewId: string, page: number): string {
  const data = `${CALLBACK_PREFIX}:${viewId}:${page}`;
  if (new TextEncoder().encode(data).length > MAX_CALLBACK_DATA_BYTES) {
    throw new Error(`pagination callback_data exceeds ${MAX_CALLBACK_DATA_BYTES} bytes: "${data}"`);
  }
  return data;
}

export interface ParsedPaginationCallback {
  viewId: string;
  page: number;
}

/** Never throws — a malformed callback must never crash the router
 * (brief §57); returns `null` for anything that doesn't match exactly. */
export function parsePaginationCallbackData(data: string): ParsedPaginationCallback | null {
  const parts = data.split(":");
  if (parts.length !== 3 || parts[0] !== CALLBACK_PREFIX) return null;
  const viewId = parts[1];
  const pageRaw = parts[2];
  if (!viewId || viewId.length === 0 || !pageRaw) return null;
  const page = Number(pageRaw);
  if (!Number.isInteger(page) || page < 1) return null;
  return { viewId, page };
}
