/**
 * Compact callback_data encoding for pagination (Phase 8 brief §19, §60):
 * `pg:{viewId}:{page}` — never JSON, filters, captions, or a Telegram
 * user id. `viewId` is a short, URL/callback-safe id (base64url, no `:`
 * in its alphabet) generated by db/repositories/result-views.ts.
 *
 * The access-request callbacks below (Phase 8/9 hotfix Part J/K) are a
 * deliberate, explicit exception to "never a Telegram user id": the admin
 * approval buttons must carry the target numeric user_id (it's the whole
 * point — no username-based guessing), and a Telegram id comfortably fits
 * within the same 64-byte limit.
 */
const CALLBACK_PREFIX = "pg";
/** Telegram's hard limit (brief §19, §75) — measured in bytes, not JS
 * string length (this data is always ASCII, so they're equal here, but
 * byte-measuring is the honest check). */
const MAX_CALLBACK_DATA_BYTES = 64;

export function buildPaginationCallbackData(viewId: string, page: number): string {
  const data = `${CALLBACK_PREFIX}:${viewId}:${page}`;
  if (new TextEncoder().encode(data).length > MAX_CALLBACK_DATA_BYTES) {
    throw new Error(`pagination callback_data exceeds ${MAX_CALLBACK_DATA_BYTES} bytes: "${data}"`);
  }
  return data;
}

export interface ParsedPaginationCallback {
  viewId: string;
  page: number;
}

/** Never throws — a malformed callback must never crash the router
 * (brief §57); returns `null` for anything that doesn't match exactly. */
export function parsePaginationCallbackData(data: string): ParsedPaginationCallback | null {
  const parts = data.split(":");
  if (parts.length !== 3 || parts[0] !== CALLBACK_PREFIX) return null;
  const viewId = parts[1];
  const pageRaw = parts[2];
  if (!viewId || viewId.length === 0 || !pageRaw) return null;
  const page = Number(pageRaw);
  if (!Number.isInteger(page) || page < 1) return null;
  return { viewId, page };
}

const ACCESS_CALLBACK_PREFIX = "access";
export type AccessDecisionAction = "allow" | "admin" | "deny";

export function buildAccessCallbackData(action: AccessDecisionAction, userId: number): string {
  const data = `${ACCESS_CALLBACK_PREFIX}:${action}:${userId}`;
  if (new TextEncoder().encode(data).length > MAX_CALLBACK_DATA_BYTES) {
    throw new Error(`access callback_data exceeds ${MAX_CALLBACK_DATA_BYTES} bytes: "${data}"`);
  }
  return data;
}

export interface ParsedAccessCallback {
  action: AccessDecisionAction;
  userId: number;
}

/** Never throws — a malformed callback must never crash the router
 * (brief §57); returns `null` for anything that doesn't match exactly. */
export function parseAccessCallbackData(data: string): ParsedAccessCallback | null {
  const parts = data.split(":");
  if (parts.length !== 3 || parts[0] !== ACCESS_CALLBACK_PREFIX) return null;
  const action = parts[1];
  if (action !== "allow" && action !== "admin" && action !== "deny") return null;
  const userId = Number(parts[2]);
  if (!Number.isInteger(userId) || userId <= 0) return null;
  return { action, userId };
}
